### ISSUE TITLE
Optional!(inout(A)) doesn't compile (bag is not stack variable)

### ISSUE THREAD

**Issue by SimonN** [aliak00/optional#12] opened 2018-03-25 00:56 UTC
Optional 0.3.1.

The following example **compiles well** :

```
import optional;

class A { }

class C {
    Optional!(const(A)) f() const
    {
        return Optional!(const(A))();
    }
}

void main() { }
```

It **fails** to compile when I change all `const` to `inout`:

```
import optional;

class A { }

class C {
    Optional!(inout(A)) f() inout
    {
        return Optional!(inout(A))();
    }
}

void main() { }
```

DMD64 D Compiler v2.079.0 says:
```
../../../.dub/packages/optional-0.3.1/optional/source/optional/optional.d(36,9): Error: variable `optional.optional.Optional!(inout(A)).Optional.bag` only parameters or stack based variables can be inout
source/app.d(6,5): Error: template instance `optional.optional.Optional!(inout(A))` error instantiating
```

I conjecture that Optional's `A[] bag` could be implemented as a `bool` + an `A` (if `A` is a class, then inside `Optional!A` it's still a reference, not an emplaced class object). Then the `A` can live on the stack, inside the `Optional!A` object. Maybe that'll make Optional `@nogc` :)

To get the range behavior, one could alias this the `Optional!A` to a function that returns empty dynamic array or a dynamic array of one element that points to the included `A`. I believe this is even robust with dynamic array capacity (the runtime or GC should know that there is no leftover capacity behind the one element).

**Comment by aliak00** [comment] 2018-03-25 20:09
Thanks for this! Yeah I think going the value + bool is a better way to go! I had a go at it a few weeks ago, but constantly ran in to const/immutable issues :(

Tried again just now. Got stuck again.

The problem is that Optional!(immutable T) is reassignable and this is possible now because T[] can be [recreated on assignment](https://github.com/aliak00/optional/blob/master/source/optional/optional.d#L70) and because dynamic arrays in D can be implicitly treated as head mutable / tail const, it seems to work. As soon as you change bag to a `T value` ... boom. I'm currently trying an approach with `Unqual!T` but that gets me stuck in the dispatcher since T loses it's qualifiers and then this ends up compiling:

```
struct A {
  void mutableMethod() {}
}

auto a = some!(immutable A());
a.dispatch.mutableMethod; // compiles >_<
```

Working on it though!

**Comment by aliak00** [comment] 2018-03-25 20:10
And oh how nice it would be to make this `@nogc`!

**Comment by SimonN** [comment] 2018-03-26 03:33
Wow, thanks for the extensive work.

I remember how I first looked at `T[] bag` 3 weeks ago and conjectured that it was to store `T[]` to store `immutable T` safely, and then forgot about this reasoning again. I'll take an extensive look at the `value` implementation.

**Comment by SimonN** [comment] 2018-03-26 06:33
I wrote a couple examples, and ended very similar to [Simen's example immutability violation](https://forum.dlang.org/post/plkusuziygdfedrblarl@forum.dlang.org):
```
import std.stdio;
import optional;

void main()
{
    Optional!(immutable int) oii = some!(immutable int)(5);
    immutable(int)* p = oii.unwrap;
    writeln(p, " -> ", *p);
    oii = 4;
    writeln(p, " -> ", *p);
}
```
Output from Optional PR #13:
```
7FFF82C0F720 -> 5
7FFF82C0F720 -> 4
```
... which shouldn't happen when `p` is `immutable(int)*`. Under Optional 0.3.1, the same code was safe:
```
Running ./bin/optional 
7F900A319000 -> 5
7F900A319000 -> 5
```
It looks like `inout` doesn't mesh well with template magic. There have even been ideas to replace `inout` entirely with more templates. I don't see how Simen's `SubstituteInout` will help, I suppose it would be used to determine the exact implementation of `Optional`?

**Comment by aliak00** [comment] 2018-03-27 06:39
Ya, seems like there may not be a sane way around this yet. This can work safely if I disable this use case:

```
Optional!(immutable int) a = 3;
a = none;
a = 4;
```

I feel like @nogc is more valuable than allowing this use case, so I'm considering just disabling the above. In your opinion do you see this as too big an inconvenience? The upside is that it'd match struct semantics in D, so it can be easily explained. The downside is that the above does seem like a rather intuitive usecase.

I'm also considering adding a `Flag` that allows one to enable the above use case at the expense of losing `@nogc`. Then we get best of both worlds.

**Comment by aliak00** [comment] 2018-03-27 06:43
>  I don't see how Simen's SubstituteInout will help, I suppose it would be used to determine the exact implementation of Optional?

Ya, not 100% sure. Usually not enough brain power to get everything Simen says :p I've asked about it though.

**Comment by SimonN** [comment] 2018-03-27 07:53
This is getting very exciting, `@nogc`, support for `inout`, and type safety must be weighed against each other -- I thought 100 % type safety should be the first priority, but, according to Jonathan, `std.Rebindable` isn't 100 % clean, it merely always works. Let's keep the `T[] bag` for a while and contemplate. It's even conceivable to split the implementation according to whether value types or references are wrapped.

It happens that my use cases are all wrapping class references. I use Optional wherever I would have used a raw class reference designed to be nullable, and I use raw class references only when null is a bug. It doesn't help me prevent runtime null crashes 100 %, but it clarifies my internal function interfaces.

When we wrap a raw D class reference of `class A`, that's already a reference type and I feel `struct Optional(A) { A value; bool isPresent }` will either be both sound and the compiler will infer `@nogc`, or it will be at least `@nogc`-inferrable and then run into the same nuanced problems of the existing `std.Rebindable`. I should study Rebindable more and join the discussion on the D forums.

Assuming that I wrap an `int` or a POD `struct` (= no pointers/references/dynamic arrays in this data), then I won't need `inout` in the first place on the function that returns this data. I would instead always return a mutable object wrapped in Optional because there can be no damage to the `const` class object from where I'm returning the POD.

**Comment by aliak00** [comment] 2018-07-30 17:40
I'm closing this now. PR #16  has reworked a lot of things as I've finally gone with a nogc implementation and followed the immutability behavior of D structs (i.e. `Optional!(immutable int)` is like `struct S { immutable int }` i.e. unassignable.

I'll be adding to it a bit here and there and will eventually merge it. So shout if there' some major problems/requests for your use case! :)

**Closed by aliak00** 2018-07-30 17:40 UTC
